In [32]:
import pandas as pd

In [33]:
data = pd.read_csv("Amazon_sales_dataset_cleaned.csv")

In [34]:
data['OrderDate']=pd.to_datetime(data['OrderDate'])

In [35]:
data.head()

,OrderID,OrderDate,CustomerID,CustomerName,ProductID,ProductName,Category,Brand,Quantity,UnitPrice,Discount,Tax,ShippingCost,TotalAmount,PaymentMethod,OrderStatus,City,State,Country,SellerID
0,ORD0000001,2023-01-31,CUST001504,Vihaan Sharma,P00014,Drone Mini,Books,BrightLux,3,106.59,0.00,0.00,0.09,319.86,Debit Card,Delivered,Washington,DC,India,SELL01967
1,ORD0000002,2023-12-30,CUST000178,Pooja Kumar,P00040,Microphone,Home & Kitchen,UrbanStyle,1,251.37,0.05,19.10,1.74,259.64,Amazon Pay,Delivered,Fort Worth,TX,United States,SELL01298
2,ORD0000003,2022-05-10,CUST047516,Sneha Singh,P00044,Power Bank 20000mAh,Clothing,UrbanStyle,3,35.03,0.10,7.57,5.91,108.06,Debit Card,Delivered,Austin,TX,United States,SELL00908
3,ORD0000004,2023-07-18,CUST030059,Vihaan Reddy,P00041,Webcam Full HD,Home & Kitchen,Zenith,5,33.58,0.15,11.42,5.53,159.66,Cash on Delivery,Delivered,Charlotte,NC,India,SELL01164
4,ORD0000005,2023-02-04,CUST048677,Aditya Kapoor,P00029,T-Shirt,Clothing,KiddoFun,2,515.64,0.25,38.67,9.23,821.36,Credit Card,Cancelled,San Antonio,TX,Canada,SELL01411

In [36]:
#============Revenue by Category==================

In [42]:
category_revenue= data.groupby('Category').agg(
    TotalRevenue = ('TotalAmount','sum'),
    OrderRevenue = ('OrderID','count')
).sort_values('TotalRevenue',ascending = False)
print("============= Revenue by Category ======================")
print(category_revenue)

============= Revenue by Category ======================
                   TotalRevenue  OrderRevenue
Category
Electronics         15584217.18         16853
Sports & Outdoors   15345571.88         16804
Books               15261837.01         16752
Clothing            15253397.50         16439
Toys & Games        15216684.99         16542
Home & Kitchen      15163939.36         16610

In [38]:
#===================Monthly sales trend=============

In [40]:
data['Month']= data['OrderDate'].dt.to_period('M')
monthly_sales = data.groupby('Month')['TotalAmount'].sum()
print("\n===================Monthly sales trend=============")
print(monthly_sales)

===================Monthly sales trend=============
Month
2020-01    1637069.40
2020-02    1339388.21
2020-03    1587125.66
2020-04    1588347.29
2020-05    1533834.17
2020-06    1500269.29
2020-07    1552981.94
2020-08    1640874.93
2020-09    1554682.21
2020-10    1515403.62
2020-11    1502232.24
2020-12    1577655.06
2021-01    1575253.23
2021-02    1425365.99
2021-03    1484165.89
2021-04    1470885.02
2021-05    1571842.25
2021-06    1593398.08
2021-07    1596668.40
2021-08    1545324.30
2021-09    1534912.30
2021-10    1511118.44
2021-11    1419480.77
2021-12    1520160.14
2022-01    1609759.87
2022-02    1369866.29
2022-03    1589809.35
2022-04    1515497.24
2022-05    1527845.26
2022-06    1533829.81
2022-07    1556516.29
2022-08    1541701.50
2022-09    1457859.60
2022-10    1534349.51
2022-11    1525937.46
2022-12    1604276.23
2023-01    1567772.07
2023-02    1384957.09
2023-03    1557146.56
2023-04    1560322.12
2023-05    1588151.65
2023-06    1485367.09
2023-07    1562298.78
2023-08    1585424.79
2023-09    1543306.82
2023-10    1573039.08
2023-11    1518312.33
2023-12    1587813.81
2024-01    1493946.70
2024-02    1412146.91
2024-03    1548280.27
2024-04    1511151.55
2024-05    1642609.94
2024-06    1541772.48
2024-07    1469460.10
2024-08    1577272.85
2024-09    1468209.92
2024-10    1520332.67
2024-11    1529791.33
2024-12    1451073.77
Freq: M, Name: TotalAmount, dtype: float64

In [43]:
# Top 10 product

In [44]:
data.head()

,OrderID,OrderDate,CustomerID,CustomerName,ProductID,ProductName,Category,Brand,Quantity,UnitPrice,...,Tax,ShippingCost,TotalAmount,PaymentMethod,OrderStatus,City,State,Country,SellerID,Month
0,ORD0000001,2023-01-31,CUST001504,Vihaan Sharma,P00014,Drone Mini,Books,BrightLux,3,106.59,...,0.00,0.09,319.86,Debit Card,Delivered,Washington,DC,India,SELL01967,2023-01
1,ORD0000002,2023-12-30,CUST000178,Pooja Kumar,P00040,Microphone,Home & Kitchen,UrbanStyle,1,251.37,...,19.10,1.74,259.64,Amazon Pay,Delivered,Fort Worth,TX,United States,SELL01298,2023-12
2,ORD0000003,2022-05-10,CUST047516,Sneha Singh,P00044,Power Bank 20000mAh,Clothing,UrbanStyle,3,35.03,...,7.57,5.91,108.06,Debit Card,Delivered,Austin,TX,United States,SELL00908,2022-05
3,ORD0000004,2023-07-18,CUST030059,Vihaan Reddy,P00041,Webcam Full HD,Home & Kitchen,Zenith,5,33.58,...,11.42,5.53,159.66,Cash on Delivery,Delivered,Charlotte,NC,India,SELL01164,2023-07
4,ORD0000005,2023-02-04,CUST048677,Aditya Kapoor,P00029,T-Shirt,Clothing,KiddoFun,2,515.64,...,38.67,9.23,821.36,Credit Card,Cancelled,San Antonio,TX,Canada,SELL01411,2023-02

In [47]:
top_product = data.groupby('ProductName').agg(
    TotalRevenue = ('TotalAmount','sum'),
    TotalQuntity = ('Quantity','sum')
).sort_values('TotalRevenue',ascending = False).head(10)
print("=================Top 10 product============================")
print(top_product)

=================Top 10 product============================
                     TotalRevenue  TotalQuntity
ProductName
Memory Card 128GB      1935138.40          6240
LED Desk Lamp          1921948.41          6344
Mechanical Keyboard    1906963.54          6161
Electric Kettle        1905751.79          6165
Smartwatch             1901275.59          5983
Dress Shirt            1896765.36          5960
Water Bottle           1895467.95          6275
Gaming Mouse           1895103.98          6170
Kids Toy Car           1891082.43          6131
Jeans                  1882591.82          6037

In [48]:
data.head()

,OrderID,OrderDate,CustomerID,CustomerName,ProductID,ProductName,Category,Brand,Quantity,UnitPrice,...,Tax,ShippingCost,TotalAmount,PaymentMethod,OrderStatus,City,State,Country,SellerID,Month
0,ORD0000001,2023-01-31,CUST001504,Vihaan Sharma,P00014,Drone Mini,Books,BrightLux,3,106.59,...,0.00,0.09,319.86,Debit Card,Delivered,Washington,DC,India,SELL01967,2023-01
1,ORD0000002,2023-12-30,CUST000178,Pooja Kumar,P00040,Microphone,Home & Kitchen,UrbanStyle,1,251.37,...,19.10,1.74,259.64,Amazon Pay,Delivered,Fort Worth,TX,United States,SELL01298,2023-12
2,ORD0000003,2022-05-10,CUST047516,Sneha Singh,P00044,Power Bank 20000mAh,Clothing,UrbanStyle,3,35.03,...,7.57,5.91,108.06,Debit Card,Delivered,Austin,TX,United States,SELL00908,2022-05
3,ORD0000004,2023-07-18,CUST030059,Vihaan Reddy,P00041,Webcam Full HD,Home & Kitchen,Zenith,5,33.58,...,11.42,5.53,159.66,Cash on Delivery,Delivered,Charlotte,NC,India,SELL01164,2023-07
4,ORD0000005,2023-02-04,CUST048677,Aditya Kapoor,P00029,T-Shirt,Clothing,KiddoFun,2,515.64,...,38.67,9.23,821.36,Credit Card,Cancelled,San Antonio,TX,Canada,SELL01411,2023-02

In [49]:
# ============ Sales by Country ==============

In [51]:
Country_Sales = data.groupby('Country').agg(
    TotalRevenue =('TotalAmount','sum'),
    OrderRevenue =('OrderID','count')
).sort_values('TotalRevenue',ascending = False)
print("==================Sales by Country ==============")
print(Country_Sales)

==================Sales by Country ==============
                TotalRevenue  OrderRevenue
Country
United States    64310048.50         70058
India            13875839.12         15051
Canada            5323757.00          5818
United Kingdom    4526896.86          4943
Australia         3789106.44          4130

In [52]:
#================= Order Status Breakdown ==============

In [56]:
Status_breakdown = data['OrderStatus'].value_counts()
Status_persent = data['OrderStatus'].value_counts(normalize=True)*100
print("\n========== Order Status Breakdown ===========")
print(pd.DataFrame({'count':Status_breakdown,'persent':Status_persent.round(2)}))

========== Order Status Breakdown ===========
             count  persent
OrderStatus
Delivered    74628    74.63
Shipped      15192    15.19
Pending       4103     4.10
Returned      3049     3.05
Cancelled     3028     3.03

In [57]:
#=================== Payment method prefernce ====================

In [58]:
data.head()

,OrderID,OrderDate,CustomerID,CustomerName,ProductID,ProductName,Category,Brand,Quantity,UnitPrice,...,Tax,ShippingCost,TotalAmount,PaymentMethod,OrderStatus,City,State,Country,SellerID,Month
0,ORD0000001,2023-01-31,CUST001504,Vihaan Sharma,P00014,Drone Mini,Books,BrightLux,3,106.59,...,0.00,0.09,319.86,Debit Card,Delivered,Washington,DC,India,SELL01967,2023-01
1,ORD0000002,2023-12-30,CUST000178,Pooja Kumar,P00040,Microphone,Home & Kitchen,UrbanStyle,1,251.37,...,19.10,1.74,259.64,Amazon Pay,Delivered,Fort Worth,TX,United States,SELL01298,2023-12
2,ORD0000003,2022-05-10,CUST047516,Sneha Singh,P00044,Power Bank 20000mAh,Clothing,UrbanStyle,3,35.03,...,7.57,5.91,108.06,Debit Card,Delivered,Austin,TX,United States,SELL00908,2022-05
3,ORD0000004,2023-07-18,CUST030059,Vihaan Reddy,P00041,Webcam Full HD,Home & Kitchen,Zenith,5,33.58,...,11.42,5.53,159.66,Cash on Delivery,Delivered,Charlotte,NC,India,SELL01164,2023-07
4,ORD0000005,2023-02-04,CUST048677,Aditya Kapoor,P00029,T-Shirt,Clothing,KiddoFun,2,515.64,...,38.67,9.23,821.36,Credit Card,Cancelled,San Antonio,TX,Canada,SELL01411,2023-02

In [59]:
payment_breakdown = data.groupby('PaymentMethod').agg(
    OrderCount = ('OrderID','count'),
    TotalRevenue = ('TotalAmount','sum')
).sort_values('OrderCount',ascending = False)
print("\n=========== Payment method prefernce ========")
print(payment_breakdown)

=========== Payment method prefernce ========
                  OrderCount  TotalRevenue
PaymentMethod
Credit Card            35038   32122158.69
Debit Card             20024   18538678.53
UPI                    15066   13896028.55
Amazon Pay             15017   13697498.42
Net Banking             9927    9055674.57
Cash on Delivery        4928    4515609.16